apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: bitcoin-investment-tracker
resources:
  - 001-namespace.yaml
  - 002-configmap.yaml
  - 003-secret.yaml
  - 004-deployment.yaml
  - 005-service.yaml
  - 006-ingress.yaml
  - 007-servicemonitor.yaml
  - 008-prometheus-rule.yaml
  - 009-alertmanager-cr.yaml
images:
  - name: ambrosiaaaaa/bitcoin-investment-tracker
    newTag: v0.0.9
# Common labels for all resources
commonLabels:
  app.kubernetes.io/managed-by: argocd
  app.kubernetes.io/part-of: bitcoin-investment-tracker
  app.kubernetes.io/environment: base
