name: Build and push bitcoin-investment-tracker container image

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - "kubernetes/.argocd-source-*.yaml"
  pull_request:
    branches: [ "main" ]

env:
  IMAGE_NAME: bitcoin-investment-tracker
  REGISTRY_USER: ambrosiaaaaa
  REGISTRY: docker.io

jobs:
  test:
    runs-on: [my-runner-bitcoin-investment-tracker]

    steps:
      # Checkout code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Setup Go with explicit cache
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'
          cache: true
          cache-dependency-path: bitcoin-fetcher-notification/go.sum

      # Check and run tests
      - name: Check and run tests
        working-directory: ./
        run: |
          if [ ! -f go.mod ] || [ ! -f go.sum ]; then
            echo "Error: go.mod or go.sum not found!"
            exit 1
          fi
          TEST_FILES=$(find . -name "*_test.go")
          if [ -z "$TEST_FILES" ]; then
             echo "Warning: No test files found, skipping tests."
          else
            go test ./... -v
          fi

  build-and-push:
    needs: test
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    steps:
      # Checkout code
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Read version from file
        id: version
        run: |
          echo "Current directory contents:"
          ls -la
          echo "----------------"
          VERSION=$(cat .version)
          echo "Read version: $VERSION" # Debug
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
          cat $GITHUB_OUTPUT # Debug of the output file

      - name: Super Debug
        run: |
          echo "Content of the VERSION file:"
          cat .version
          echo "----------------"
          echo "Output of the previous step:"
          echo "${{ steps.version.outputs.VERSION }}"
          echo "----------------"
          echo "Complete tag that will be used:"
          echo "${{ env.REGISTRY }}/${{ env.REGISTRY_USER }}/${{ env.IMAGE_NAME }}:${{ steps.version.outputs.VERSION }}"

      - name: Check if DOCKERHUB_TOKEN is set
        run: |
          if [ -z "${{ secrets.DOCKERHUB_TOKEN }}" ]; then
            echo "Error: DOCKERHUB_TOKEN is not set! Please configure the secret in your repository settings."
            exit 1
          else
            echo "DOCKERHUB_TOKEN is properly configured."
          fi
      
      - name: Debug credentials
        run: |
          echo "Registry: ${{ env.REGISTRY }}"
          echo "Username: ${{ env.REGISTRY_USER }}"
          echo "Token set: ${{ secrets.DOCKERHUB_TOKEN != '' }}"
        env:
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

      # Login to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: docker.io
          username: ${{ env.REGISTRY_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Build and push
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ./
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ env.REGISTRY }}/${{ env.REGISTRY_USER }}/${{ env.IMAGE_NAME }}:${{ steps.version.outputs.VERSION }}
